### PR TITLE
Function to install Firefox and start it

### PR DESCRIPTION
**Pull request by Ronqn**
Added a function to install Firefox ESR, Ublock Origin and launch Firefox once to create the profile folder.

### CODE REVIEW

**Comment by Ronqn** [comment]
To make it better, I've modified the way firefox-esr starts so it starts in another Shell. Then the script waits 5 seconds and kill all the firefox processes. This way, the user won't need to manually click to close the Firefox window.

**Comment by MystixCode** [comment]
just a different problem. when i start firefox and check in the settings or in the prefs.js file the config isnt done -.-
no idea why.

**Comment by MystixCode** [comment]
just wanted to suggest that ;)

**Comment by Ronqn** [comment]
Not working with user.js too.
If I go inside "user.js", it's empty. If I go inside "prefs.js", the settings are the default one.. Strange!

**Comment by Ronqn** [comment]
You beat me to it, I just finished testing with a slightly different command but it works aswell.
Implementing your code and committing when it's done in a few minutes! :-)

**Comment by Ronqn** [comment]
It writes correctly in the "user.js" file right now with the added $path lol, thanks!
Now just to clean the code a bit and it should work correctly.

**Comment by Ronqn** [comment]
Thanks, this was fun helping you! 👍

**Pull request merged**
